// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { Provider } from '../../../weidmueller/ucontrol/hub/provider.js';
/**
 * A list of providers that provide variables to consumers.
 */
export class ProviderList {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsProviderList(bb, obj) {
        return (obj || new ProviderList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsProviderList(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new ProviderList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    /**
     * The list of providers.
     */
    items(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? (obj || new Provider()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    itemsLength() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    static startProviderList(builder) {
        builder.startObject(1);
    }
    static addItems(builder, itemsOffset) {
        builder.addFieldOffset(0, itemsOffset, 0);
    }
    static createItemsVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startItemsVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static endProviderList(builder) {
        const offset = builder.endObject();
        return offset;
    }
    static createProviderList(builder, itemsOffset) {
        ProviderList.startProviderList(builder);
        ProviderList.addItems(builder, itemsOffset);
        return ProviderList.endProviderList(builder);
    }
    unpack() {
        return new ProviderListT(this.bb.createObjList(this.items.bind(this), this.itemsLength()));
    }
    unpackTo(_o) {
        _o.items = this.bb.createObjList(this.items.bind(this), this.itemsLength());
    }
}
export class ProviderListT {
    constructor(items = []) {
        this.items = items;
    }
    pack(builder) {
        const items = ProviderList.createItemsVector(builder, builder.createObjectOffsetList(this.items));
        return ProviderList.createProviderList(builder, items);
    }
}
