// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
/**
 * A provider that provides variables to consumers.
 */
export class Provider {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsProvider(bb, obj) {
        return (obj || new Provider()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsProvider(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Provider()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    id(optionalEncoding) {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.__string(this.bb_pos + offset, optionalEncoding) : null;
    }
    static startProvider(builder) {
        builder.startObject(1);
    }
    static addId(builder, idOffset) {
        builder.addFieldOffset(0, idOffset, 0);
    }
    static endProvider(builder) {
        const offset = builder.endObject();
        builder.requiredField(offset, 4); // id
        return offset;
    }
    static createProvider(builder, idOffset) {
        Provider.startProvider(builder);
        Provider.addId(builder, idOffset);
        return Provider.endProvider(builder);
    }
    unpack() {
        return new ProviderT(this.id());
    }
    unpackTo(_o) {
        _o.id = this.id();
    }
}
export class ProviderT {
    constructor(id = null) {
        this.id = id;
    }
    pack(builder) {
        const id = (this.id !== null ? builder.createString(this.id) : 0);
        return Provider.createProvider(builder, id);
    }
}
