// automatically generated by the FlatBuffers compiler, do not modify
/**
 * A timestamp measured by the number of nanoseconds that have elapsed
 * since 00:00:00 UTC on 1 January 1970, which is referred to as the Unix
 * epoch, without adjustments made due to leap seconds.
 *
 * Based on google protobuf timestamp definition: <https://github.com/protocolbuffers/protobuf/blob/main/src/google/protobuf/timestamp.proto>
 */
export class Timestamp {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    /**
     * Represents seconds of UTC time since Unix epoch
     * 1970-01-01T00:00:00Z. Must be from 0001-01-01T00:00:00Z to
     * 9999-12-31T23:59:59Z inclusive.
     */
    seconds() {
        return this.bb.readInt64(this.bb_pos);
    }
    /**
     * Non-negative fractions of a second at nanosecond resolution. Negative
     * second values with fractions must still have non-negative nanos values
     * that count forward in time. Must be from 0 to 999,999,999
     * inclusive.
     */
    nanos() {
        return this.bb.readInt32(this.bb_pos + 8);
    }
    static sizeOf() {
        return 16;
    }
    static createTimestamp(builder, seconds, nanos) {
        builder.prep(8, 16);
        builder.pad(4);
        builder.writeInt32(nanos);
        builder.writeInt64(BigInt(seconds ?? 0));
        return builder.offset();
    }
    unpack() {
        return new TimestampT(this.seconds(), this.nanos());
    }
    unpackTo(_o) {
        _o.seconds = this.seconds();
        _o.nanos = this.nanos();
    }
}
export class TimestampT {
    constructor(seconds = BigInt('0'), nanos = 0) {
        this.seconds = seconds;
        this.nanos = nanos;
    }
    pack(builder) {
        return Timestamp.createTimestamp(builder, this.seconds, this.nanos);
    }
}
