// automatically generated by the FlatBuffers compiler, do not modify
export class Uuid {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    upper() {
        return this.bb.readUint64(this.bb_pos);
    }
    lower() {
        return this.bb.readUint64(this.bb_pos + 8);
    }
    static sizeOf() {
        return 16;
    }
    static createUuid(builder, upper, lower) {
        builder.prep(8, 16);
        builder.writeInt64(BigInt(lower ?? 0));
        builder.writeInt64(BigInt(upper ?? 0));
        return builder.offset();
    }
    unpack() {
        return new UuidT(this.upper(), this.lower());
    }
    unpackTo(_o) {
        _o.upper = this.upper();
        _o.lower = this.lower();
    }
}
export class UuidT {
    constructor(upper = BigInt('0'), lower = BigInt('0')) {
        this.upper = upper;
        this.lower = lower;
    }
    pack(builder) {
        return Uuid.createUuid(builder, this.upper, this.lower);
    }
}
