// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { Timestamp } from '../../../weidmueller/ucontrol/hub/timestamp.js';
import { VariableQuality } from '../../../weidmueller/ucontrol/hub/variable-quality.js';
import { VariableValue, unionToVariableValue } from '../../../weidmueller/ucontrol/hub/variable-value.js';
/**
 * A variable associated with the provider's definition.
 */
export class Variable {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsVariable(bb, obj) {
        return (obj || new Variable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsVariable(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new Variable()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    valueType() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint8(this.bb_pos + offset) : VariableValue.NONE;
    }
    /**
     * The value of the variable.
     */
    value(obj) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? this.bb.__union(obj, this.bb_pos + offset) : null;
    }
    /**
     * The ID of the variable associated with the provider's definition.
     */
    id() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.readUint32(this.bb_pos + offset) : 0;
    }
    /**
     * The individual timestamp of the variable.
     *
     * Only set by the provider!
     * Consumers can left this empty. This value is ignored by the provider in
     * a write command.
     */
    timestamp(obj) {
        const offset = this.bb.__offset(this.bb_pos, 10);
        return offset ? (obj || new Timestamp()).__init(this.bb_pos + offset, this.bb) : null;
    }
    /**
     * The quality of the variable.
     *
     * Only set by the provider!
     * Consumers can set it to BAD. This value is ignored by the provider
     * in a write command.
     */
    quality() {
        const offset = this.bb.__offset(this.bb_pos, 12);
        return offset ? this.bb.readUint8(this.bb_pos + offset) : VariableQuality.BAD;
    }
    static startVariable(builder) {
        builder.startObject(5);
    }
    static addValueType(builder, valueType) {
        builder.addFieldInt8(0, valueType, VariableValue.NONE);
    }
    static addValue(builder, valueOffset) {
        builder.addFieldOffset(1, valueOffset, 0);
    }
    static addId(builder, id) {
        builder.addFieldInt32(2, id, 0);
    }
    static addTimestamp(builder, timestampOffset) {
        builder.addFieldStruct(3, timestampOffset, 0);
    }
    static addQuality(builder, quality) {
        builder.addFieldInt8(4, quality, VariableQuality.BAD);
    }
    static endVariable(builder) {
        const offset = builder.endObject();
        // builder.requiredField(offset, 6); // value - Removed to prevent crash in JS runtime
        return offset;
    }
    unpack() {
        return new VariableT(this.valueType(), (() => {
            const temp = unionToVariableValue(this.valueType(), this.value.bind(this));
            if (temp === null) {
                return null;
            }
            return temp.unpack();
        })(), this.id(), (this.timestamp() !== null ? this.timestamp().unpack() : null), this.quality());
    }
    unpackTo(_o) {
        _o.valueType = this.valueType();
        _o.value = (() => {
            const temp = unionToVariableValue(this.valueType(), this.value.bind(this));
            if (temp === null) {
                return null;
            }
            return temp.unpack();
        })();
        _o.id = this.id();
        _o.timestamp = (this.timestamp() !== null ? this.timestamp().unpack() : null);
        _o.quality = this.quality();
    }
}
export class VariableT {
    constructor(valueType = VariableValue.NONE, value = null, id = 0, timestamp = null, quality = VariableQuality.BAD) {
        this.valueType = valueType;
        this.value = value;
        this.id = id;
        this.timestamp = timestamp;
        this.quality = quality;
    }
    pack(builder) {
        let value = 0;
        if (this.value !== null) {
            value = this.value.pack(builder);
        }
        Variable.startVariable(builder);
        Variable.addValueType(builder, this.valueType);
        Variable.addValue(builder, value);
        Variable.addId(builder, this.id);
        Variable.addTimestamp(builder, (this.timestamp !== null ? this.timestamp.pack(builder) : 0));
        Variable.addQuality(builder, this.quality);
        return Variable.endVariable(builder);
    }
}
