// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import * as flatbuffers from 'flatbuffers';
import { Timestamp } from '../../../weidmueller/ucontrol/hub/timestamp.js';
import { Variable } from '../../../weidmueller/ucontrol/hub/variable.js';
/**
 * A list of a provider's variables that match the provider's definition.
 */
export class VariableList {
    constructor() {
        this.bb = null;
        this.bb_pos = 0;
    }
    __init(i, bb) {
        this.bb_pos = i;
        this.bb = bb;
        return this;
    }
    static getRootAsVariableList(bb, obj) {
        return (obj || new VariableList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    static getSizePrefixedRootAsVariableList(bb, obj) {
        bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
        return (obj || new VariableList()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
    }
    /**
     * The fingerprint of the associated provider's definition.
     */
    providerDefinitionFingerprint() {
        const offset = this.bb.__offset(this.bb_pos, 4);
        return offset ? this.bb.readUint64(this.bb_pos + offset) : BigInt('0');
    }
    /**
     * The timestamp for all changed variables. The base timestamp is the
     * fallback if no explicit was specified for the variable.
     *
     * Only set by the provider!
     * Consumers can set it to 0s and 0ns. This value is ignored by the
     * provider in a write command.
     */
    baseTimestamp(obj) {
        const offset = this.bb.__offset(this.bb_pos, 6);
        return offset ? (obj || new Timestamp()).__init(this.bb_pos + offset, this.bb) : null;
    }
    /**
     * The items of the provider's variable list.
     */
    items(index, obj) {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? (obj || new Variable()).__init(this.bb.__indirect(this.bb.__vector(this.bb_pos + offset) + index * 4), this.bb) : null;
    }
    itemsLength() {
        const offset = this.bb.__offset(this.bb_pos, 8);
        return offset ? this.bb.__vector_len(this.bb_pos + offset) : 0;
    }
    static startVariableList(builder) {
        builder.startObject(3);
    }
    static addProviderDefinitionFingerprint(builder, providerDefinitionFingerprint) {
        builder.addFieldInt64(0, providerDefinitionFingerprint, BigInt('0'));
    }
    static addBaseTimestamp(builder, baseTimestampOffset) {
        builder.addFieldStruct(1, baseTimestampOffset, 0);
    }
    static addItems(builder, itemsOffset) {
        builder.addFieldOffset(2, itemsOffset, 0);
    }
    static createItemsVector(builder, data) {
        builder.startVector(4, data.length, 4);
        for (let i = data.length - 1; i >= 0; i--) {
            builder.addOffset(data[i]);
        }
        return builder.endVector();
    }
    static startItemsVector(builder, numElems) {
        builder.startVector(4, numElems, 4);
    }
    static endVariableList(builder) {
        const offset = builder.endObject();
        // builder.requiredField(offset, 6); // base_timestamp - DISABLED for stability
        return offset;
    }
    unpack() {
        return new VariableListT(this.providerDefinitionFingerprint(), (this.baseTimestamp() !== null ? this.baseTimestamp().unpack() : null), this.bb.createObjList(this.items.bind(this), this.itemsLength()));
    }
    unpackTo(_o) {
        _o.providerDefinitionFingerprint = this.providerDefinitionFingerprint();
        _o.baseTimestamp = (this.baseTimestamp() !== null ? this.baseTimestamp().unpack() : null);
        _o.items = this.bb.createObjList(this.items.bind(this), this.itemsLength());
    }
}
export class VariableListT {
    constructor(providerDefinitionFingerprint = BigInt('0'), baseTimestamp = null, items = []) {
        this.providerDefinitionFingerprint = providerDefinitionFingerprint;
        this.baseTimestamp = baseTimestamp;
        this.items = items;
    }
    pack(builder) {
        const items = VariableList.createItemsVector(builder, builder.createObjectOffsetList(this.items));
        const baseTimestampOffset = this.baseTimestamp !== null ? this.baseTimestamp.pack(builder) : 0;

        VariableList.startVariableList(builder);
        VariableList.addBaseTimestamp(builder, baseTimestampOffset);
        VariableList.addProviderDefinitionFingerprint(builder, this.providerDefinitionFingerprint);
        VariableList.addItems(builder, items);

        return VariableList.endVariableList(builder);
    }
}
