// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
/**
 * The quality of a variable.
 *
 * This is set by the provider and indicates the quality of a variable value.
 * Check the documentation of the individual values for more information.
 */
export var VariableQuality;
(function (VariableQuality) {
    /**
     * Indicates that the value is not usable
     */
    VariableQuality[VariableQuality["BAD"] = 0] = "BAD";
    /**
     * Variable quality is uncertain without any specific reason, but may still be usable e.g. for display or other non critical purposes
     */
    VariableQuality[VariableQuality["UNCERTAIN"] = 64] = "UNCERTAIN";
    /**
     * The variable has stopped updating and contains its last usable value
     */
    VariableQuality[VariableQuality["UNCERTAIN_LAST_USABLE_VALUE"] = 67] = "UNCERTAIN_LAST_USABLE_VALUE";
    /**
     * Variable has not been written yet and still contains a default initial value
     */
    VariableQuality[VariableQuality["UNCERTAIN_INITIAL_VALUE"] = 68] = "UNCERTAIN_INITIAL_VALUE";
    /**
     * Indicates that the value is good and can be used without restrictions
     */
    VariableQuality[VariableQuality["GOOD"] = 192] = "GOOD";
})(VariableQuality || (VariableQuality = {}));
