// automatically generated by the FlatBuffers compiler, do not modify
/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */
import { VariableValueBoolean } from '../../../weidmueller/ucontrol/hub/variable-value-boolean.js';
import { VariableValueDuration } from '../../../weidmueller/ucontrol/hub/variable-value-duration.js';
import { VariableValueFloat64 } from '../../../weidmueller/ucontrol/hub/variable-value-float64.js';
import { VariableValueInt64 } from '../../../weidmueller/ucontrol/hub/variable-value-int64.js';
import { VariableValueString } from '../../../weidmueller/ucontrol/hub/variable-value-string.js';
import { VariableValueTimestamp } from '../../../weidmueller/ucontrol/hub/variable-value-timestamp.js';
/**
 * The value of a variable.
 */
export var VariableValue;
(function (VariableValue) {
    VariableValue[VariableValue["NONE"] = 0] = "NONE";
    VariableValue[VariableValue["Boolean"] = 1] = "Boolean";
    VariableValue[VariableValue["Duration"] = 2] = "Duration";
    VariableValue[VariableValue["Float64"] = 3] = "Float64";
    VariableValue[VariableValue["Int64"] = 4] = "Int64";
    VariableValue[VariableValue["String"] = 5] = "String";
    VariableValue[VariableValue["Timestamp"] = 6] = "Timestamp";
})(VariableValue || (VariableValue = {}));
export function unionToVariableValue(type, accessor) {
    switch (VariableValue[type]) {
        case 'NONE': return null;
        case 'Boolean': return accessor(new VariableValueBoolean());
        case 'Duration': return accessor(new VariableValueDuration());
        case 'Float64': return accessor(new VariableValueFloat64());
        case 'Int64': return accessor(new VariableValueInt64());
        case 'String': return accessor(new VariableValueString());
        case 'Timestamp': return accessor(new VariableValueTimestamp());
        default: return null;
    }
}
export function unionListToVariableValue(type, accessor, index) {
    switch (VariableValue[type]) {
        case 'NONE': return null;
        case 'Boolean': return accessor(index, new VariableValueBoolean());
        case 'Duration': return accessor(index, new VariableValueDuration());
        case 'Float64': return accessor(index, new VariableValueFloat64());
        case 'Int64': return accessor(index, new VariableValueInt64());
        case 'String': return accessor(index, new VariableValueString());
        case 'Timestamp': return accessor(index, new VariableValueTimestamp());
        default: return null;
    }
}
